server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://auth-db:5432/auth_db
    username: auth_user
    password: auth_password

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

app:
  jwt:
    public-key: classpath:keys/public.pem
    private-key: classpath:keys/private.pem