server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://servicos-db:5432/servicos_db
    username: servicos_user
    password: servicos_password

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:keys/public.pem
